root@ip-10-0-0-49:/var/log# cat cloud-init.log
2025-10-30 07:21:40,355 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'init-local' at Thu, 30 Oct 2025 07:21:40 +0000. Up 6.22 seconds.
2025-10-30 07:21:40,355 - main.py[INFO]: PID [1] started cloud-init 'init-local'.
2025-10-30 07:21:40,355 - main.py[DEBUG]: No kernel command line url found.
2025-10-30 07:21:40,355 - main.py[DEBUG]: Closing stdin
2025-10-30 07:21:40,360 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-10-30 07:21:40,360 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-10-30 07:21:40,360 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2025-10-30 07:21:40,361 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2025-10-30 07:21:40,361 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2025-10-30 07:21:40,361 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-10-30 07:21:40,361 - stages.py[DEBUG]: no cache found
2025-10-30 07:21:40,361 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2025-10-30 07:21:40,364 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:40,364 - sources[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2025-10-30 07:21:40,388 - sources[DEBUG]: Searching for local data source in: ['DataSourceEc2Local']
2025-10-30 07:21:40,388 - handlers.py[DEBUG]: start: init-local/search-Ec2Local: searching for local data from DataSourceEc2Local
2025-10-30 07:21:40,388 - sources[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2Local'>
2025-10-30 07:21:40,388 - sources[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-10-30 07:21:40,388 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-10-30 07:21:40,388 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-10-30 07:21:40,388 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-10-30 07:21:40,388 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-10-30 07:21:40,388 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-10-30 07:21:40,388 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2025-10-30 07:21:40,389 - sources[DEBUG]: Detected DataSourceEc2Local
2025-10-30 07:21:40,389 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-10-30 07:21:40,389 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-10-30 07:21:40,389 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/name_assign_type
2025-10-30 07:21:40,389 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:40,389 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:40,389 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-10-30 07:21:40,390 - net[DEBUG]: Interface has no carrier: ens5
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading from /sys/class/net/ens5/dormant (quiet=False)
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading from /sys/class/net/ens5/operstate (quiet=False)
2025-10-30 07:21:40,390 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/ens5/operstate
2025-10-30 07:21:40,390 - ephemeral.py[DEBUG]: No connectivity URLs provided. Skipping connectivity check before ephemeral network setup.
2025-10-30 07:21:40,390 - ephemeral.py[DEBUG]: No connectivity to IMDS, attempting DHCP setup.
2025-10-30 07:21:40,390 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:40,437 - performance.py[DEBUG]: Running ['ip', '--json', 'addr'] took 0.046 seconds
2025-10-30 07:21:40,437 - ephemeral.py[DEBUG]: No connectivity URLs provided. Skipping connectivity check before ephemeral network setup.
2025-10-30 07:21:40,437 - distros[DEBUG]: Using configured dhcp client priority list: ['dhcpcd', 'dhclient', 'udhcpc']
2025-10-30 07:21:40,437 - distros[DEBUG]: DHCP client selected: dhcpcd
2025-10-30 07:21:40,437 - dhcp.py[DEBUG]: Performing a dhcp discovery on ens5
2025-10-30 07:21:40,437 - subp.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'ens5', 'up'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:40,443 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-30 07:21:40,443 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/type
2025-10-30 07:21:40,443 - subp.py[DEBUG]: Running command ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'ens5'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,428 - performance.py[DEBUG]: Running ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'ens5'] took 0.984 seconds
2025-10-30 07:21:41,428 - subp.py[DEBUG]: Running command ['dhcpcd', '--dumplease', '--ipv4only', 'ens5'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,432 - dhcp.py[DEBUG]: Parsing dhcpcd lease for interface ens5: 'reason=BOUND\ninterface=ens5\nprotocol=dhcp\nip_address=10.0.0.49\nsubnet_cidr=24\nnetwork_number=10.0.0.0\nsubnet_mask=255.255.255.0\nrouters=10.0.0.1\ndomain_name_servers=10.0.0.2\nhost_name=ip-10-0-0-49\ndomain_name=ap-southeast-1.compute.internal\ninterface_mtu=9001\nbroadcast_address=10.0.0.255\ndhcp_lease_time=3600\ndhcp_message_type=5\ndhcp_server_identifier=10.0.0.1\n'
2025-10-30 07:21:41,432 - util.py[DEBUG]: Reading from /var/lib/dhcpcd/ens5.lease (quiet=False)
2025-10-30 07:21:41,432 - util.py[DEBUG]: Reading 548 bytes from /var/lib/dhcpcd/ens5.lease
2025-10-30 07:21:41,432 - subp.py[DEBUG]: Running command ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'ens5', '-P'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,434 - util.py[DEBUG]: Reading from /run/dhcpcd/ens5-4.pid (quiet=False)
2025-10-30 07:21:41,434 - util.py[DEBUG]: Reading 4 bytes from /run/dhcpcd/ens5-4.pid
2025-10-30 07:21:41,434 - util.py[DEBUG]: Reading from /proc/468/stat (quiet=True)
2025-10-30 07:21:41,434 - util.py[DEBUG]: Reading 304 bytes from /proc/468/stat
2025-10-30 07:21:41,434 - dhcp.py[DEBUG]: killing dhcpcd with pid=468 gid=467
2025-10-30 07:21:41,435 - ephemeral.py[DEBUG]: Received dhcp lease on ens5 for 10.0.0.49/255.255.255.0
2025-10-30 07:21:41,435 - ephemeral.py[DEBUG]: Attempting setup of ephemeral network on ens5 with 10.0.0.49/24 brd 10.0.0.255
2025-10-30 07:21:41,435 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,437 - ephemeral.py[DEBUG]: Skip adding ip address: ens5 already has address 10.0.0.49
2025-10-30 07:21:41,437 - ephemeral.py[DEBUG]: Skip bringing up network link: interface ens5 is already up
2025-10-30 07:21:41,437 - subp.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,438 - ephemeral.py[DEBUG]: Skip ephemeral route setup. ens5 already has default route: default via 10.0.0.1 dev ens5 proto dhcp src 10.0.0.49 metric 1002 mtu 9001
2025-10-30 07:21:41,439 - ephemeral.py[DEBUG]: Successfully brought up ens5 for ephemeral ipv4 networking.
2025-10-30 07:21:41,439 - util.py[DEBUG]: Reading from /sys/class/net/ens5/operstate (quiet=False)
2025-10-30 07:21:41,439 - util.py[DEBUG]: Reading 3 bytes from /sys/class/net/ens5/operstate
2025-10-30 07:21:41,439 - ephemeral.py[DEBUG]: Successfully brought up ens5 for ephemeral ipv6 networking.
2025-10-30 07:21:41,443 - DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
2025-10-30 07:21:41,443 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-10-30 07:21:41,444 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'stream': False, 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,455 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
2025-10-30 07:21:41,456 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2025-10-30 07:21:41,456 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,458 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-30 07:21:41,458 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-10-30 07:21:41,458 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/user-data' with {'url': 'http://169.254.169.254/2021-03-23/user-data', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,460 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,461 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2025-10-30 07:21:41,462 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,463 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ (200, 30b) after 1 attempts
2025-10-30 07:21:41,463 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,465 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-10-30 07:21:41,465 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,467 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral0 (200, 3b) after 1 attempts
2025-10-30 07:21:41,467 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,468 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/ephemeral1 (200, 3b) after 1 attempts
2025-10-30 07:21:41,469 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,470 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-10-30 07:21:41,470 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,472 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-10-30 07:21:41,472 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,473 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-10-30 07:21:41,474 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,475 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-10-30 07:21:41,475 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,477 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-10-30 07:21:41,477 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/iam/', 'stream': False, 'allow_redirects':True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,478 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-10-30 07:21:41,479 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/iam/info', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,480 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/iam/info (200, 215b) after 1 attempts
2025-10-30 07:21:41,480 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,482 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-10-30 07:21:41,482 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,483 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-10-30 07:21:41,484 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,485 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-10-30 07:21:41,485 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/metrics/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,487 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-10-30 07:21:41,487 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,489 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-10-30 07:21:41,489 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,491 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-10-30 07:21:41,491 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,493 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-10-30 07:21:41,493 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,494 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-10-30 07:21:41,495 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,501 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ (200, 230b) after 1 attempts
2025-10-30 07:21:41,501 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,503 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/ (200, 13b) after 1 attempts
2025-10-30 07:21:41,503 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/54.255.189.63' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/54.255.189.63', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,505 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/ipv4-associations/54.255.189.63 (200, 9b) after 1 attempts
2025-10-30 07:21:41,505 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/device-number' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/device-number', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,507 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/device-number (200, 1b) after 1 attempts
2025-10-30 07:21:41,507 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/interface-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/interface-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,509 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/interface-id (200, 21b) after 1 attempts
2025-10-30 07:21:41,509 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,510 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-hostname (200, 44b) after 1 attempts
2025-10-30 07:21:41,511 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-ipv4s' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-ipv4s', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,512 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/local-ipv4s (200, 9b) after 1 attempts
2025-10-30 07:21:41,512 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/mac' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/mac', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,514 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/mac (200, 17b) after 1 attempts
2025-10-30 07:21:41,514 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/owner-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/owner-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,516 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/owner-id (200, 12b) after 1 attempts
2025-10-30 07:21:41,516 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent':'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,517 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-hostname (200, 54b) after 1 attempts
2025-10-30 07:21:41,518 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-ipv4s' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-ipv4s', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,519 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/public-ipv4s (200, 13b) after 1 attempts
2025-10-30 07:21:41,519 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-group-ids' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-group-ids', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,522 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-group-ids (200, 20b) after 1 attempts
2025-10-30 07:21:41,522 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-groups' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-groups', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent':'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,524 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/security-groups (200, 15b) after 1 attempts
2025-10-30 07:21:41,524 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,525 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-id (200, 24b) after 1 attempts
2025-10-30 07:21:41,525 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-ipv4-cidr-block', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED','User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,527 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
2025-10-30 07:21:41,527 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,529 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-id (200, 21b) after 1 attempts
2025-10-30 07:21:41,529 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-block', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,530 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
2025-10-30 07:21:41,531 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-blocks', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,532 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/network/interfaces/macs/02:17:b4:41:f5:e7/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
2025-10-30 07:21:41,532 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,534 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-10-30 07:21:41,534 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,543 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone (200, 15b) after 1 attempts
2025-10-30 07:21:41,543 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,546 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/availability-zone-id (200, 9b) after 1 attempts
2025-10-30 07:21:41,546 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/placement/region', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,548 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/placement/region (200, 14b) after 1 attempts
2025-10-30 07:21:41,548 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,550 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-10-30 07:21:41,550 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/domain', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,552 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-10-30 07:21:41,552 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/services/partition', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,554 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-10-30 07:21:41,554 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,556 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-10-30 07:21:41,556 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-launch-index', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,558 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-10-30 07:21:41,558 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path', 'stream':False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,560 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-10-30 07:21:41,560 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,561 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/hostname (200, 44b) after 1 attempts
2025-10-30 07:21:41,562 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-action', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,563 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-10-30 07:21:41,564 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,565 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-30 07:21:41,565 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,567 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-10-30 07:21:41,567 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/instance-type', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,568 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-10-30 07:21:41,569 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/local-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,570 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/local-hostname (200, 44b) after 1 attempts
2025-10-30 07:21:41,570 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/local-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,571 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/local-ipv4 (200, 9b) after 1 attempts
2025-10-30 07:21:41,572 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/mac', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,573 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-10-30 07:21:41,574 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/profile', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,575 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-10-30 07:21:41,575 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,576 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-hostname (200, 54b) after 1 attempts
2025-10-30 07:21:41,577 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/public-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,578 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2025-10-30 07:21:41,578 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/reservation-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,579 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-10-30 07:21:41,580 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254/2021-03-23/meta-data/security-groups', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,581 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/meta-data/security-groups (200, 15b) after 1 attempts
2025-10-30 07:21:41,581 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,583 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-10-30 07:21:41,583 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/document', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,584 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/document (200, 483b) after 1 attempts
2025-10-30 07:21:41,585 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,586 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1179b) after 1 attempts
2025-10-30 07:21:41,586 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,588 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1499b) after 1 attempts
2025-10-30 07:21:41,588 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED', 'User-Agent': 'Cloud-Init/25.1.4-0ubuntu0~24.04.1'}} configuration
2025-10-30 07:21:41,589 - url_helper.py[DEBUG]: Read from http://169.254.169.254/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-10-30 07:21:41,589 - DataSourceEc2.py[DEBUG]: Crawled metadata service using link-local ipv6
2025-10-30 07:21:41,590 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'ens5', 'down'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,593 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '10.0.0.49/24', 'dev', 'ens5'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,596 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-10-30 07:21:41,597 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-10-30 07:21:41,597 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpfg5sl7xi) - w: [600] 14419 bytes/chars
2025-10-30 07:21:41,598 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmp9e68ekc9) - w: [644] 7864 bytes/chars
2025-10-30 07:21:41,598 - performance.py[DEBUG]: Getting metadata took 1.210 seconds
2025-10-30 07:21:41,598 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2025-10-30 07:21:41,598 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-30 07:21:41,598 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
2025-10-30 07:21:41,598 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-30 07:21:41,599 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-10-30 07:21:41,599 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,606 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-10-30 07:21:41,606 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-10-30 07:21:41,606 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,608 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-10-30 07:21:41,608 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-10-30 07:21:41,608 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,608 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-30 07:21:41,608 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-30 07:21:41,608 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,610 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-30 07:21:41,610 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-10-30 07:21:41,610 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,610 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,611 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:41,611 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-30 07:21:41,611 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0910d9dd6af987762'
2025-10-30 07:21:41,612 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0910d9dd6af987762/datasource (quiet=False)
2025-10-30 07:21:41,612 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/datasource - wb: [644] 39 bytes
2025-10-30 07:21:41,612 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2025-10-30 07:21:41,612 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-10-30 07:21:41,613 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-10-30 07:21:41,613 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-10-30 07:21:41,613 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-10-30 07:21:41,613 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-10-30 07:21:41,614 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12209 bytes
2025-10-30 07:21:41,614 - main.py[DEBUG]: [local] init will now be targeting instance id: i-0910d9dd6af987762. new=True
2025-10-30 07:21:41,614 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-30 07:21:41,614 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-10-30 07:21:41,614 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,621 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-10-30 07:21:41,621 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-10-30 07:21:41,621 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,622 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-10-30 07:21:41,622 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-10-30 07:21:41,622 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,623 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-30 07:21:41,623 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-30 07:21:41,623 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,625 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-30 07:21:41,625 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-10-30 07:21:41,625 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,625 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:41,625 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:41,626 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:41,626 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-0-49.ap-southeast-1.compute.internal (ip-10-0-0-49)
2025-10-30 07:21:41,626 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2025-10-30 07:21:41,627 - util.py[DEBUG]: Reading 7 bytes from /etc/hostname
2025-10-30 07:21:41,627 - util.py[DEBUG]: Writing to /etc/hostname - wb: [644] 13 bytes
2025-10-30 07:21:41,627 - distros[DEBUG]: Non-persistently setting the system hostname to ip-10-0-0-49
2025-10-30 07:21:41,627 - subp.py[DEBUG]: Running command ['hostname', 'ip-10-0-0-49'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,630 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpz74fx2lg) - w: [644] 89 bytes/chars
2025-10-30 07:21:41,630 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,630 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,630 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,630 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/name_assign_type
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-10-30 07:21:41,631 - net[DEBUG]: Interface has no carrier: ens5
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/dormant (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/operstate (quiet=False)
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/ens5/operstate
2025-10-30 07:21:41,631 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/ens5/uevent
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,632 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/type
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-10-30 07:21:41,632 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-10-30 07:21:41,634 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-10-30 07:21:41,634 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,634 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,635 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,635 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,635 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/instance/network-config.json (via temporary file /var/lib/cloud/instance/tmpwntiwgs4) - w: [600] 171 bytes/chars
2025-10-30 07:21:41,635 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/network-config.json' => '/var/lib/cloud/instance/network-config.json'
2025-10-30 07:21:41,635 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-10-30 07:21:41,636 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-10-30 07:21:41,637 - schema.py[DEBUG]: Validating network-config with netplan API
2025-10-30 07:21:41,638 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmp_mlbi8k2/etc/netplan/network-config.yaml - wb: [600] 202 bytes
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/ens5/uevent
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-30 07:21:41,639 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/type
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-10-30 07:21:41,640 - networking.py[DEBUG]: net: all expected physical devices present
2025-10-30 07:21:41,640 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'ens5': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '02:17:b4:41:f5:e7'}, 'set-name': 'ens5'}}}
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/ens5/uevent
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-30 07:21:41,640 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading from /sys/class/net/ens5/operstate (quiet=False)
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading 5 bytes from /sys/class/net/ens5/operstate
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2025-10-30 07:21:41,641 - util.py[DEBUG]: Reading 8 bytes from /sys/class/net/lo/operstate
2025-10-30 07:21:41,641 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,643 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:41,645 - net[DEBUG]: Detected interfaces {'ens5': {'downable': True, 'device_id': '0xec20', 'driver': 'ena', 'mac': '02:17:b4:41:f5:e7', 'name': 'ens5', 'up': False}, 'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}}
2025-10-30 07:21:41,645 - net[DEBUG]: no work necessary for renaming of [['02:17:b4:41:f5:e7', 'ens5', 'ena', '0xec20']]
2025-10-30 07:21:41,645 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 2, 'ethernets': {'ens5': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '02:17:b4:41:f5:e7'}, 'set-name': 'ens5'}}}
2025-10-30 07:21:41,646 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2025-10-30 07:21:41,646 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-10-30 07:21:41,646 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-10-30 07:21:41,647 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-10-30 07:21:41,648 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-10-30 07:21:41,648 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:42,275 - performance.py[DEBUG]: Running ['netplan', 'generate'] took 0.627 seconds
2025-10-30 07:21:42,275 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens5'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:42,279 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:42,284 - distros[DEBUG]: Not bringing up newly configured network interfaces
2025-10-30 07:21:42,284 - main.py[DEBUG]: [local] Exiting. datasource DataSourceEc2Local not in local mode.
2025-10-30 07:21:42,284 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-30 07:21:42,284 - util.py[DEBUG]: Reading 10 bytes from /proc/uptime
2025-10-30 07:21:42,285 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpwfgqiwwm) - w: [644] 499 bytes/chars
2025-10-30 07:21:42,285 - performance.py[DEBUG]: cloud-init stage: 'init-local' took 1.978 seconds
2025-10-30 07:21:42,285 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2025-10-30 07:21:44,584 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'init' at Thu, 30 Oct 2025 07:21:44 +0000. Up 10.44 seconds.
2025-10-30 07:21:44,584 - main.py[INFO]: PID [1] started cloud-init 'init'.
2025-10-30 07:21:44,584 - main.py[DEBUG]: No kernel command line url found.
2025-10-30 07:21:44,584 - main.py[DEBUG]: Closing stdin
2025-10-30 07:21:44,586 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-10-30 07:21:44,586 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-10-30 07:21:44,586 - util.py[DEBUG]: Reading from /var/lib/cloud/data/python-version (quiet=False)
2025-10-30 07:21:44,587 - util.py[DEBUG]: Reading 4 bytes from /var/lib/cloud/data/python-version
2025-10-30 07:21:44,587 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,589 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,591 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-10-30 07:21:44,593 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-10-30 07:21:44,594 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-10-30 07:21:44,594 - util.py[DEBUG]: Reading 12209 bytes from /var/lib/cloud/instance/obj.pkl
2025-10-30 07:21:44,598 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2025-10-30 07:21:44,598 - util.py[DEBUG]: Reading 20 bytes from /run/cloud-init/.instance-id
2025-10-30 07:21:44,598 - stages.py[DEBUG]: restored from cache with run check: DataSourceEc2Local
2025-10-30 07:21:44,598 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceEc2Local
2025-10-30 07:21:44,598 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-30 07:21:44,599 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-10-30 07:21:44,599 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,609 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-10-30 07:21:44,610 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-10-30 07:21:44,610 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,611 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-10-30 07:21:44,612 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-10-30 07:21:44,612 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,612 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-30 07:21:44,612 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-30 07:21:44,612 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,615 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-30 07:21:44,615 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-10-30 07:21:44,615 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,616 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,616 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:44,617 - stages.py[INFO]: Instance link already exists, not recreating it.
2025-10-30 07:21:44,617 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0910d9dd6af987762/datasource (quiet=False)
2025-10-30 07:21:44,617 - util.py[DEBUG]: Reading 39 bytes from /var/lib/cloud/instances/i-0910d9dd6af987762/datasource
2025-10-30 07:21:44,617 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/datasource - wb: [644] 39 bytes
2025-10-30 07:21:44,618 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 39 bytes
2025-10-30 07:21:44,618 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-10-30 07:21:44,618 - util.py[DEBUG]: Reading 20 bytes from /var/lib/cloud/data/instance-id
2025-10-30 07:21:44,618 - stages.py[DEBUG]: previous iid found to be i-0910d9dd6af987762
2025-10-30 07:21:44,618 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-10-30 07:21:44,619 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-10-30 07:21:44,619 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
2025-10-30 07:21:44,620 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12398 bytes
2025-10-30 07:21:44,620 - stages.py[INFO]: Not re-loading configuration, instance id and datasource have not changed.
2025-10-30 07:21:44,620 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0910d9dd6af987762. new=False
2025-10-30 07:21:44,621 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:44,621 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:44,621 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:44,621 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/ens5/uevent
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:44,622 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:44,622 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/type
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-10-30 07:21:44,623 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-10-30 07:21:44,623 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-10-30 07:21:44,624 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2025-10-30 07:21:44,624 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2025-10-30 07:21:44,624 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.HOTPLUG: 'hotplug'>, <EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2025-10-30 07:21:44,624 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2025-10-30 07:21:44,624 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2025-10-30 07:21:44,624 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'ens5': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '02:17:b4:41:f5:e7'}, 'set-name': 'ens5'}}}
2025-10-30 07:21:44,625 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-30 07:21:44,625 - util.py[DEBUG]: Reading 25 bytes from /sys/class/net/ens5/uevent
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens5/address
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens5/device/device
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/ens5/operstate (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 3 bytes from /sys/class/net/ens5/operstate
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2025-10-30 07:21:44,626 - util.py[DEBUG]: Reading 8 bytes from /sys/class/net/lo/operstate
2025-10-30 07:21:44,627 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,641 - performance.py[DEBUG]: Running ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] took 0.014 seconds
2025-10-30 07:21:44,641 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,643 - net[DEBUG]: Detected interfaces {'ens5': {'downable': False, 'device_id': '0xec20', 'driver': 'ena', 'mac': '02:17:b4:41:f5:e7', 'name': 'ens5', 'up': True}, 'lo': {'downable': False, 'device_id': None, 'driver': None, 'mac': '00:00:00:00:00:00', 'name': 'lo', 'up': True}}
2025-10-30 07:21:44,643 - net[DEBUG]: no work necessary for renaming of [['02:17:b4:41:f5:e7', 'ens5', 'ena', '0xec20']]
2025-10-30 07:21:44,643 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-10-30 07:21:44,643 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-10-30 07:21:44,643 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/user-data.txt - wb: [600] 0 bytes
2025-10-30 07:21:44,646 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/user-data.txt.i - wb: [600] 308 bytes
2025-10-30 07:21:44,646 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/vendor-data.txt - wb: [600] 0 bytes
2025-10-30 07:21:44,647 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/vendor-data.txt.i - wb: [600] 308 bytes
2025-10-30 07:21:44,647 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/vendor-data2.txt - wb: [600] 0 bytes
2025-10-30 07:21:44,648 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/vendor-data2.txt.i - wb: [600] 308 bytes
2025-10-30 07:21:44,649 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-10-30 07:21:44,649 - util.py[DEBUG]: Reading 89 bytes from /var/lib/cloud/data/set-hostname
2025-10-30 07:21:44,649 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set_hostname
2025-10-30 07:21:44,649 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/consume_data - wb: [644] 24 bytes
2025-10-30 07:21:44,649 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/consume_data'>)
2025-10-30 07:21:44,649 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-10-30 07:21:44,649 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-10-30 07:21:44,650 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-10-30 07:21:44,650 - handlers[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"'}
2025-10-30 07:21:44,651 - handlers[DEBUG]: Empty payload of type text/x-not-multipart
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-10-30 07:21:44,651 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/cloud-config.txt - wb: [600] 0 bytes
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-10-30 07:21:44,651 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-10-30 07:21:44,651 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-10-30 07:21:44,651 - stages.py[DEBUG]: no vendordata from datasource
2025-10-30 07:21:44,651 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-10-30 07:21:44,651 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-10-30 07:21:44,651 - stages.py[DEBUG]: no vendordata2 from datasource
2025-10-30 07:21:44,651 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-10-30 07:21:44,651 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-30 07:21:44,652 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-10-30 07:21:44,652 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,659 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-10-30 07:21:44,659 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-10-30 07:21:44,659 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,660 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg (quiet=False)
2025-10-30 07:21:44,660 - util.py[DEBUG]: Reading 108 bytes from /etc/cloud/cloud.cfg.d/90-cpc-grub.cfg
2025-10-30 07:21:44,660 - util.py[DEBUG]: Attempting to load yaml from string of length 108 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,660 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-30 07:21:44,660 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-30 07:21:44,660 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,662 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-30 07:21:44,662 - util.py[DEBUG]: Reading 31 bytes from /run/cloud-init/cloud.cfg
2025-10-30 07:21:44,662 - util.py[DEBUG]: Attempting to load yaml from string of length 31 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,663 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,663 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:44,663 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-30 07:21:44,663 - util.py[DEBUG]: Reading 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-30 07:21:44,663 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,663 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:44,664 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/combined-cloud-config.json (via temporary file /run/cloud-init/tmpyfesoz9y) - w: [600] 5609 bytes/chars
2025-10-30 07:21:44,664 - util.py[DEBUG]: Reading from /run/cloud-init/instance-data-sensitive.json (quiet=False)
2025-10-30 07:21:44,664 - util.py[DEBUG]: Reading 14419 bytes from /run/cloud-init/instance-data-sensitive.json
2025-10-30 07:21:44,665 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpernbzshp) - w: [600] 16650 bytes/chars
2025-10-30 07:21:44,665 - main.py[DEBUG]: Skipping user-data validation. No user-data found.
2025-10-30 07:21:44,666 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-30 07:21:44,666 - util.py[DEBUG]: Reading 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-30 07:21:44,666 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-30 07:21:44,666 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-30 07:21:44,667 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-10-30 07:21:44,668 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 14821 bytes
2025-10-30 07:21:44,668 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-10-30 07:21:44,668 - main.py[DEBUG]: no di_report found in config.
2025-10-30 07:21:44,682 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:44,683 - modules.py[INFO]: Skipping modules 'bootcmd,write_files,disk_setup,update_etc_hosts,ca_certs,rsyslog' because no applicable config is provided.
2025-10-30 07:21:44,684 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-10-30 07:21:44,684 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-10-30 07:21:44,684 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_seed_random - wb: [644] 24 bytes
2025-10-30 07:21:44,684 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_seed_random'>)
2025-10-30 07:21:44,684 - cc_seed_random.py[DEBUG]: no command provided
2025-10-30 07:21:44,684 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully and took 0.001 seconds
2025-10-30 07:21:44,684 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-10-30 07:21:44,685 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-10-30 07:21:44,685 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f4fc6b46510>)
2025-10-30 07:21:44,685 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-10-30 07:21:44,685 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,697 - performance.py[DEBUG]: Running ['growpart', '--help'] took 0.012 seconds
2025-10-30 07:21:44,697 - util.py[DEBUG]: Reading from /proc/545/mountinfo (quiet=False)
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading 2665 bytes from /proc/545/mountinfo
2025-10-30 07:21:44,698 - cc_growpart.py[DEBUG]: growpart found fs=ext4
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading from /proc/545/mountinfo (quiet=False)
2025-10-30 07:21:44,698 - util.py[DEBUG]: Reading 2665 bytes from /proc/545/mountinfo
2025-10-30 07:21:44,699 - util.py[DEBUG]: Reading from /proc/545/mountinfo (quiet=False)
2025-10-30 07:21:44,699 - util.py[DEBUG]: Reading 2665 bytes from /proc/545/mountinfo
2025-10-30 07:21:44,699 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,835 - performance.py[DEBUG]: Running ['growpart', '--dry-run', '/dev/nvme0n1', '1'] took 0.136 seconds
2025-10-30 07:21:44,835 - performance.py[DEBUG]: Resizing devices took 0.138 seconds
2025-10-30 07:21:44,835 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-10-30 07:21:44,835 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully and took 0.151 seconds
2025-10-30 07:21:44,835 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-10-30 07:21:44,836 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-10-30 07:21:44,836 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f4fc6b46600>)
2025-10-30 07:21:44,836 - util.py[DEBUG]: Reading from /proc/545/mountinfo (quiet=False)
2025-10-30 07:21:44,836 - util.py[DEBUG]: Reading 2665 bytes from /proc/545/mountinfo
2025-10-30 07:21:44,836 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/root mnt_point=/ path=/
2025-10-30 07:21:44,836 - cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/root
2025-10-30 07:21:44,836 - subp.py[DEBUG]: Running command ('resize2fs', '/dev/root') with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,841 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=ext4, val=True)
2025-10-30 07:21:44,841 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully and took 0.005 seconds
2025-10-30 07:21:44,841 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-10-30 07:21:44,841 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-10-30 07:21:44,841 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_mounts - wb: [644] 24 bytes
2025-10-30 07:21:44,841 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_mounts'>)
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-10-30 07:21:44,842 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-10-30 07:21:44,842 - util.py[DEBUG]: Reading 146 bytes from /etc/fstab
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: changed ephemeral0 => None
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-10-30 07:21:44,842 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: changed swap => None
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: no need to setup swap
2025-10-30 07:21:44,842 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-10-30 07:21:44,842 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully and took 0.001 seconds
2025-10-30 07:21:44,842 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2025-10-30 07:21:44,842 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2025-10-30 07:21:44,843 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_set_hostname - wb: [644] 23 bytes
2025-10-30 07:21:44,843 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_set_hostname'>)
2025-10-30 07:21:44,843 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-10-30 07:21:44,843 - util.py[DEBUG]: Reading 89 bytes from /var/lib/cloud/data/set-hostname
2025-10-30 07:21:44,843 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set_hostname
2025-10-30 07:21:44,843 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully and took 0.001 seconds
2025-10-30 07:21:44,843 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-10-30 07:21:44,843 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-10-30 07:21:44,843 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f4fc6b457f0>)
2025-10-30 07:21:44,843 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-0-49.ap-southeast-1.compute.internal (ip-10-0-0-49)
2025-10-30 07:21:44,844 - util.py[DEBUG]: Reading from /etc/hostname (quiet=False)
2025-10-30 07:21:44,844 - util.py[DEBUG]: Reading 13 bytes from /etc/hostname
2025-10-30 07:21:44,844 - distros[DEBUG]: Attempting to update hostname to ip-10-0-0-49 in 1 files
2025-10-30 07:21:44,844 - util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
2025-10-30 07:21:44,844 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 13 bytes
2025-10-30 07:21:44,844 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully and took 0.001 seconds
2025-10-30 07:21:44,844 - modules.py[DEBUG]: Running module users_groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-10-30 07:21:44,844 - handlers.py[DEBUG]: start: init-network/config-users_groups: running config-users_groups with frequency once-per-instance
2025-10-30 07:21:44,844 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_users_groups - wb: [644] 24 bytes
2025-10-30 07:21:44,845 - helpers.py[DEBUG]: Running config-users_groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_users_groups'>)
2025-10-30 07:21:44,846 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-10-30 07:21:44,846 - util.py[DEBUG]: Reading 400 bytes from /etc/os-release
2025-10-30 07:21:44,846 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-10-30 07:21:44,846 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-10-30 07:21:44,846 - distros[DEBUG]: Adding user ubuntu
2025-10-30 07:21:44,846 - subp.py[DEBUG]: Running command ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,cdrom,dip,lxd,sudo', '--shell', '/bin/bash', '-m'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,904 - performance.py[DEBUG]: Running ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,cdrom,dip,lxd,sudo', '--shell', '/bin/bash', '-m'] took 0.057 seconds
2025-10-30 07:21:44,904 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ubuntu'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:44,923 - performance.py[DEBUG]: Running ['passwd', '-l', 'ubuntu'] took 0.019 seconds
2025-10-30 07:21:44,923 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-10-30 07:21:44,924 - util.py[DEBUG]: Reading 1800 bytes from /etc/sudoers
2025-10-30 07:21:44,925 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 141 bytes
2025-10-30 07:21:44,925 - handlers.py[DEBUG]: finish: init-network/config-users_groups: SUCCESS: config-users_groups ran successfully and took 0.081 seconds
2025-10-30 07:21:44,925 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-10-30 07:21:44,925 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-10-30 07:21:44,925 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh - wb: [644] 24 bytes
2025-10-30 07:21:44,926 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh'>)
2025-10-30 07:21:44,926 - util.py[DEBUG]: Reading from /proc/sys/crypto/fips_enabled (quiet=False)
2025-10-30 07:21:44,926 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:45,671 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] took 0.745 seconds
2025-10-30 07:21:45,671 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:45,677 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading 179 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading 99 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2025-10-30 07:21:45,683 - util.py[DEBUG]: Reading 571 bytes from /etc/ssh/ssh_host_rsa_key.pub
2025-10-30 07:21:45,684 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-30 07:21:45,684 - util.py[DEBUG]: Reading 3517 bytes from /etc/ssh/sshd_config
2025-10-30 07:21:45,685 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh to 1000:1000
2025-10-30 07:21:45,685 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-30 07:21:45,685 - util.py[DEBUG]: Changing the ownership of /home/ubuntu/.ssh/authorized_keys to 1000:1000
2025-10-30 07:21:45,685 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2025-10-30 07:21:45,685 - util.py[DEBUG]: Reading 0 bytes from /home/ubuntu/.ssh/authorized_keys
2025-10-30 07:21:45,685 - util.py[DEBUG]: Writing to /home/ubuntu/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-30 07:21:45,686 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-30 07:21:45,686 - util.py[DEBUG]: Reading 3517 bytes from /etc/ssh/sshd_config
2025-10-30 07:21:45,686 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-30 07:21:45,687 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-10-30 07:21:45,687 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-10-30 07:21:45,687 - util.py[DEBUG]: Reading 0 bytes from /root/.ssh/authorized_keys
2025-10-30 07:21:45,687 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-30 07:21:45,687 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully and took 0.762 seconds
2025-10-30 07:21:45,687 - modules.py[DEBUG]: Running module set_passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequencyonce-per-instance
2025-10-30 07:21:45,687 - handlers.py[DEBUG]: start: init-network/config-set_passwords: running config-set_passwords with frequency once-per-instance
2025-10-30 07:21:45,688 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_set_passwords - wb: [644] 24 bytes
2025-10-30 07:21:45,688 - helpers.py[DEBUG]: Running config-set_passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_set_passwords'>)
2025-10-30 07:21:45,688 - cc_set_passwords.py[DEBUG]: Leaving SSH config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2025-10-30 07:21:45,688 - handlers.py[DEBUG]: finish: init-network/config-set_passwords: SUCCESS: config-set_passwords ran successfully and took 0.000 seconds
2025-10-30 07:21:45,688 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-10-30 07:21:45,688 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-30 07:21:45,688 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-10-30 07:21:45,688 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpymtek7_p) - w: [644] 501 bytes/chars
2025-10-30 07:21:45,689 - performance.py[DEBUG]: cloud-init stage: 'init-network' took 1.145 seconds
2025-10-30 07:21:45,689 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-10-30 07:21:47,191 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Thu, 30 Oct 2025 07:21:47 +0000. Up 12.97 seconds.
2025-10-30 07:21:47,191 - main.py[INFO]: PID [1] started cloud-init 'modules:config'.
2025-10-30 07:21:47,220 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:47,222 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt_pipelining,ubuntu_pro,ntp,timezone,disable_ec2_metadata,runcmd' because no applicable config is provided.
2025-10-30 07:21:47,222 - modules.py[DEBUG]: Running module ssh_import_id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequencyonce-per-instance
2025-10-30 07:21:47,223 - handlers.py[DEBUG]: start: modules-config/config-ssh_import_id: running config-ssh_import_id with frequency once-per-instance
2025-10-30 07:21:47,223 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh_import_id - wb: [644] 24 bytes
2025-10-30 07:21:47,223 - helpers.py[DEBUG]: Running config-ssh_import_id using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh_import_id'>)
2025-10-30 07:21:47,223 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh_import_id, no 'ssh_import_id' directives found.
2025-10-30 07:21:47,224 - handlers.py[DEBUG]: finish: modules-config/config-ssh_import_id: SUCCESS: config-ssh_import_id ran successfully and took 0.001 seconds
2025-10-30 07:21:47,224 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-10-30 07:21:47,224 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-10-30 07:21:47,224 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_locale - wb: [644] 24 bytes
2025-10-30 07:21:47,224 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_locale'>)
2025-10-30 07:21:47,224 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2025-10-30 07:21:47,225 - util.py[DEBUG]: Reading 13 bytes from /etc/default/locale
2025-10-30 07:21:47,225 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8
2025-10-30 07:21:47,225 - debian.py[DEBUG]: System locale set to C.UTF-8 via /etc/default/locale
2025-10-30 07:21:47,225 - debian.py[DEBUG]: System has 'LANG=C.UTF-8' requested 'C.UTF-8', skipping regeneration.
2025-10-30 07:21:47,225 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully and took 0.001 seconds
2025-10-30 07:21:47,225 - modules.py[DEBUG]: Running module grub_dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2025-10-30 07:21:47,225 - handlers.py[DEBUG]: start: modules-config/config-grub_dpkg: running config-grub_dpkg with frequency once-per-instance
2025-10-30 07:21:47,225 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_grub_dpkg - wb: [644] 22 bytes
2025-10-30 07:21:47,226 - helpers.py[DEBUG]: Running config-grub_dpkg using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_grub_dpkg'>)
2025-10-30 07:21:47,226 - cc_grub_dpkg.py[DEBUG]: grub_dpkg disabled by config grub_dpkg/enabled=False
2025-10-30 07:21:47,226 - handlers.py[DEBUG]: finish: modules-config/config-grub_dpkg: SUCCESS: config-grub_dpkg ran successfully and took 0.001 seconds
2025-10-30 07:21:47,226 - modules.py[DEBUG]: Running module apt_configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequencyonce-per-instance
2025-10-30 07:21:47,226 - handlers.py[DEBUG]: start: modules-config/config-apt_configure: running config-apt_configure with frequency once-per-instance
2025-10-30 07:21:47,226 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_apt_configure - wb: [644] 24 bytes
2025-10-30 07:21:47,227 - helpers.py[DEBUG]: Running config-apt_configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_apt_configure'>)
2025-10-30 07:21:47,227 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2025-10-30 07:21:47,227 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-10-30 07:21:47,227 - util.py[DEBUG]: Reading 400 bytes from /etc/os-release
2025-10-30 07:21:47,228 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-10-30 07:21:47,228 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-10-30 07:21:47,228 - cc_apt_configure.py[DEBUG]: handling apt config: {}
2025-10-30 07:21:47,228 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:47,264 - performance.py[DEBUG]: Running ['lsb_release', '--all'] took 0.036 seconds
2025-10-30 07:21:47,264 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:47,266 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2025-10-30 07:21:47,267 - cc_apt_configure.py[DEBUG]: got security mirror: None
2025-10-30 07:21:47,268 - util.py[DEBUG]: search for mirror in candidates: '['http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/', 'http://ap-southeast-1a.clouds.archive.ubuntu.com/ubuntu/', 'http://ap-southeast-1.clouds.archive.ubuntu.com/ubuntu/']'
2025-10-30 07:21:47,276 - util.py[DEBUG]: found working mirror: 'http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/'
2025-10-30 07:21:47,276 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-10-30 07:21:47,276 - distros[DEBUG]: filtered distro mirror info: {'primary': 'http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/', 'security': 'http://security.ubuntu.com/ubuntu'}
2025-10-30 07:21:47,276 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'MIRROR': 'http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/'}
2025-10-30 07:21:47,288 - cc_apt_configure.py[INFO]: No custom template provided, fall back to builtin
2025-10-30 07:21:47,293 - util.py[DEBUG]: Reading from /etc/cloud/templates/sources.list.ubuntu.deb822.tmpl (quiet=False)
2025-10-30 07:21:47,294 - util.py[DEBUG]: Reading 3091 bytes from /etc/cloud/templates/sources.list.ubuntu.deb822.tmpl
2025-10-30 07:21:47,307 - performance.py[DEBUG]: Rendering jinja2 template took 0.012 seconds
2025-10-30 07:21:47,308 - util.py[DEBUG]: Writing to /etc/apt/sources.list.d/ubuntu.sources - wb: [644] 3008 bytes
2025-10-30 07:21:47,310 - util.py[DEBUG]: Reading from /etc/apt/sources.list (quiet=False)
2025-10-30 07:21:47,311 - util.py[DEBUG]: Reading 270 bytes from /etc/apt/sources.list
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_cnf_Commands-amd64 to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_cnf_Commands-amd64
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_i18n_Translation-en to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_i18n_Translation-en
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_InRelease to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_InRelease
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_binary-amd64_Packages to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_binary-amd64_Packages
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_cnf_Commands-amd64 to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_cnf_Commands-amd64
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_InRelease to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_InRelease
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_i18n_Translation-en to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_i18n_Translation-en
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_i18n_Translation-en to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_i18n_Translation-en
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_binary-amd64_Packages to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_binary-amd64_Packages
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_restricted_binary-amd64_Packages to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_restricted_binary-amd64_Packages
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_cnf_Commands-amd64 to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_cnf_Commands-amd64
2025-10-30 07:21:47,313 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_cnf_Commands-amd64 to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_cnf_Commands-amd64
2025-10-30 07:21:47,314 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_restricted_dep11_Components-amd64.yml.gz
2025-10-30 07:21:47,314 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_binary-amd64_Packages to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_binary-amd64_Packages
2025-10-30 07:21:47,314 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_dep11_Components-amd64.yml.gz
2025-10-30 07:21:47,314 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble-updates_main_i18n_Translation-en to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble-updates_main_i18n_Translation-en
2025-10-30 07:21:47,314 - cc_apt_configure.py[DEBUG]: Renaming apt list /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_noble_main_dep11_Components-amd64.yml.gz to /var/lib/apt/lists/ap-southeast-1.ec2.archive.ubuntu.com_ubuntu_dists_noble_main_dep11_Components-amd64.yml.gz
2025-10-30 07:21:47,314 - handlers.py[DEBUG]: finish: modules-config/config-apt_configure: SUCCESS: config-apt_configure ran successfully and took 0.088 seconds
2025-10-30 07:21:47,314 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2025-10-30 07:21:47,315 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2025-10-30 07:21:47,315 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_byobu - wb: [644] 22 bytes
2025-10-30 07:21:47,315 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_byobu'>)
2025-10-30 07:21:47,315 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2025-10-30 07:21:47,316 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully and took 0.001 seconds
2025-10-30 07:21:47,316 - main.py[DEBUG]: Ran 5 modules with 0 failures
2025-10-30 07:21:47,316 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-30 07:21:47,316 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-10-30 07:21:47,316 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpvrcinz0w) - w: [644] 503 bytes/chars
2025-10-30 07:21:47,317 - performance.py[DEBUG]: cloud-init stage: 'modules-config' took 0.295 seconds
2025-10-30 07:21:47,317 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-10-30 07:21:52,368 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Thu, 30 Oct 2025 07:21:52 +0000. Up 18.18 seconds.
2025-10-30 07:21:52,368 - main.py[INFO]: PID [1] started cloud-init 'modules:final'.
2025-10-30 07:21:52,398 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-10-30 07:21:52,401 - modules.py[INFO]: Skipping modules 'package_update_upgrade_install,fan,landscape,lxd,ubuntu_drivers,write_files_deferred,puppet,chef,ansible,mcollective,salt_minion,phone_home,power_state_change' because no applicable config is provided.
2025-10-30 07:21:52,402 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2025-10-30 07:21:52,402 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2025-10-30 07:21:52,402 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_reset_rmc - wb: [644] 25 bytes
2025-10-30 07:21:52,403 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_reset_rmc'>)
2025-10-30 07:21:52,403 - cc_reset_rmc.py[DEBUG]: module disabled, RSCT_PATH not present
2025-10-30 07:21:52,403 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully and took 0.001 seconds
2025-10-30 07:21:52,403 - modules.py[DEBUG]: Running module scripts_vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2025-10-30 07:21:52,404 - handlers.py[DEBUG]: start: modules-final/config-scripts_vendor: running config-scripts_vendor with frequency once-per-instance
2025-10-30 07:21:52,404 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_vendor - wb: [644] 23 bytes
2025-10-30 07:21:52,404 - helpers.py[DEBUG]: Running config-scripts_vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_vendor'>)
2025-10-30 07:21:52,404 - handlers.py[DEBUG]: finish: modules-final/config-scripts_vendor: SUCCESS: config-scripts_vendor ran successfully and took 0.000 seconds
2025-10-30 07:21:52,404 - modules.py[DEBUG]: Running module scripts_per_once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2025-10-30 07:21:52,404 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_once: running config-scripts_per_once with frequency once
2025-10-30 07:21:52,405 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2025-10-30 07:21:52,405 - helpers.py[DEBUG]: Running config-scripts_per_once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2025-10-30 07:21:52,405 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_once: SUCCESS: config-scripts_per_once ran successfully and took 0.001 seconds
2025-10-30 07:21:52,405 - modules.py[DEBUG]: Running module scripts_per_boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2025-10-30 07:21:52,405 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_boot: running config-scripts_per_boot with frequency always
2025-10-30 07:21:52,406 - helpers.py[DEBUG]: Running config-scripts_per_boot using lock (<cloudinit.helpers.DummyLock object at 0x751cb631da00>)
2025-10-30 07:21:52,406 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_boot: SUCCESS: config-scripts_per_boot ran successfully and took 0.000 seconds
2025-10-30 07:21:52,406 - modules.py[DEBUG]: Running module scripts_per_instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2025-10-30 07:21:52,406 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_instance: running config-scripts_per_instance with frequency once-per-instance
2025-10-30 07:21:52,406 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_per_instance - wb: [644] 25 bytes
2025-10-30 07:21:52,406 - helpers.py[DEBUG]: Running config-scripts_per_instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_per_instance'>)
2025-10-30 07:21:52,407 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_instance: SUCCESS: config-scripts_per_instance ran successfully and took 0.001 seconds
2025-10-30 07:21:52,407 - modules.py[DEBUG]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2025-10-30 07:21:52,407 - handlers.py[DEBUG]: start: modules-final/config-scripts_user: running config-scripts_user with frequency once-per-instance
2025-10-30 07:21:52,407 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_user - wb: [644] 25 bytes
2025-10-30 07:21:52,407 - helpers.py[DEBUG]: Running config-scripts_user using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_scripts_user'>)
2025-10-30 07:21:52,407 - handlers.py[DEBUG]: finish: modules-final/config-scripts_user: SUCCESS: config-scripts_user ran successfully and took 0.001 seconds
2025-10-30 07:21:52,407 - modules.py[DEBUG]: Running module ssh_authkey_fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2025-10-30 07:21:52,408 - handlers.py[DEBUG]: start: modules-final/config-ssh_authkey_fingerprints: running config-ssh_authkey_fingerprints with frequency once-per-instance
2025-10-30 07:21:52,408 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2025-10-30 07:21:52,408 - helpers.py[DEBUG]: Running config-ssh_authkey_fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_ssh_authkey_fingerprints'>)
2025-10-30 07:21:52,409 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-30 07:21:52,409 - util.py[DEBUG]: Reading 3517 bytes from /etc/ssh/sshd_config
2025-10-30 07:21:52,409 - util.py[DEBUG]: Reading from /home/ubuntu/.ssh/authorized_keys (quiet=False)
2025-10-30 07:21:52,409 - util.py[DEBUG]: Reading 0 bytes from /home/ubuntu/.ssh/authorized_keys
2025-10-30 07:21:52,411 - handlers.py[DEBUG]: finish: modules-final/config-ssh_authkey_fingerprints: SUCCESS: config-ssh_authkey_fingerprints ran successfully and took 0.002 seconds
2025-10-30 07:21:52,411 - modules.py[DEBUG]: Running module keys_to_console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2025-10-30 07:21:52,411 - handlers.py[DEBUG]: start: modules-final/config-keys_to_console: running config-keys_to_console with frequency once-per-instance
2025-10-30 07:21:52,411 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_keys_to_console - wb: [644] 25 bytes
2025-10-30 07:21:52,411 - helpers.py[DEBUG]: Running config-keys_to_console using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_keys_to_console'>)
2025-10-30 07:21:52,412 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:52,462 - performance.py[DEBUG]: Running ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] took 0.050 seconds
2025-10-30 07:21:52,462 - handlers.py[DEBUG]: finish: modules-final/config-keys_to_console: SUCCESS: config-keys_to_console ran successfully and took 0.051 seconds
2025-10-30 07:21:52,462 - modules.py[DEBUG]: Running module install_hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2025-10-30 07:21:52,463 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-10-30 07:21:52,463 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_install_hotplug - wb: [644] 24 bytes
2025-10-30 07:21:52,463 - helpers.py[DEBUG]: Running config-install_hotplug using lock (<FileLock using file '/var/lib/cloud/instances/i-0910d9dd6af987762/sem/config_install_hotplug'>)
2025-10-30 07:21:52,464 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2025-10-30 07:21:52,464 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2025-10-30 07:21:52,464 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>, <EventType.HOTPLUG: 'hotplug'>}}
2025-10-30 07:21:52,464 - stages.py[DEBUG]: Event Allowed: scope=network EventType=hotplug
2025-10-30 07:21:52,464 - cc_install_hotplug.py[INFO]: Installing hotplug.
2025-10-30 07:21:52,464 - util.py[DEBUG]: Writing to /etc/udev/rules.d/90-cloud-init-hook-hotplug.rules - wb: [644] 288 bytes
2025-10-30 07:21:52,464 - subp.py[DEBUG]: Running command ['udevadm', 'control', '--reload-rules'] with allowed return codes [0] (shell=False, capture=True)
2025-10-30 07:21:52,519 - performance.py[DEBUG]: Running ['udevadm', 'control', '--reload-rules'] took 0.054 seconds
2025-10-30 07:21:52,519 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug ran successfully and took 0.056 seconds
2025-10-30 07:21:52,519 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequencyalways
2025-10-30 07:21:52,519 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-10-30 07:21:52,520 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x751cb6315070>)
2025-10-30 07:21:52,520 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-30 07:21:52,520 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-10-30 07:21:52,526 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Thu, 30 Oct 2025 07:21:52 +0000. Datasource DataSourceEc2Local.  Up 18.40 seconds
2025-10-30 07:21:52,527 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-10-30 07:21:52,527 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.007 seconds
2025-10-30 07:21:52,527 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-10-30 07:21:52,527 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-30 07:21:52,527 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-10-30 07:21:52,528 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8rvihgsn) - w: [644] 504 bytes/chars
2025-10-30 07:21:52,528 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp81rqbqrd) - w: [644] 69 bytes/chars
2025-10-30 07:21:52,528 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-10-30 07:21:52,528 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.261 seconds
2025-10-30 07:21:52,529 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final